version: '3.6'
services:
  postgres:
    # image: postgres
    image: timescale/timescaledb:latest-pg10
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data

  graphql:
    image: hasura/graphql-engine:v1.0.0-alpha07
    ports:
    - "80"
    depends_on:
    - "postgres"
    restart: always
    command: >
      /bin/sh -c "
      graphql-engine \
        --host postgres \
        --port 5432 \
        --user $POSTGRES_USER \
        --password $POSTGRES_PASSWORD \
        --dbname $POSTGRES_DB \
        serve \
        --server-port 80 \
        --enable-console;
      "

  cron-controller:
    build: ./controllers/cron
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER

volumes:
  db_data:

networks:
  default:
    external:
      name: monitor